name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.2
  sqflite: ^2.4.0
  syncfusion_flutter_chat:
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.5
  cloud_functions: ^5.1.4
  firebase_data_connect: ^0.1.2+2
  logging: ^1.0.2
  dropdown_button2: ^2.3.9
  numberpicker: ^2.1.0
  board_datetime_picker: ^2.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/fonts/
